import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactNode } from "react";
import Counter from "@/components/molecules/counter";
import Header from "@/components/organisms/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
					<header className="site-header">
						<div className="container">
							<Header title="NextJS Lesson" description="" />
							<nav className="nav">
								<Link href="/products">Products</Link>
								<Link href="/articles">Articles</Link>
								<Link href="/users">Users</Link>
								<Link href="/hangman">Game</Link>
								<Counter />
							</nav>
						</div>
					</header>
				{children}
			</body>
		</html>
	);
}
